In [2]:
import numpy as np
import pandas as pd 
from scipy import stats
import matplotlib.pyplot as plt

In [3]:
update_prof = {'Episódico/Epidêmico':'Episodic/Epidemic', 'Epidêmico':'Epidemic', 'Episódico':'Episodic',
       'Transmissão Persistente':'Persistent Transmission', 'Sem transmissão': 'No Transmission', 
              'Sem transmissao': 'No Transmission'}

In [5]:
df_10_19 = pd.read_csv('../Determinantes/clima/clima_agg_10_19.csv', index_col = 'Unnamed: 0')

df_10_19.loc[:, 'dengue_pattern'] = df_10_19.dengue_pattern.replace(update_prof)

df_10_19['period'] = '10_19'

df_10_19.head()

,geocodigo,temp_med,umid_med,precip_tot,thr_temp,thr_umid,thr_prec,thr_temp_umid,year,dengue_pattern,period
0,2700102,25.917411,71.160050,174.737289,364,314,2,314,2010,Episodic/Epidemic,10_19
1,2700201,25.484200,80.407899,424.205669,364,364,5,364,2010,Episodic/Epidemic,10_19
2,2700300,25.588142,77.216115,277.945870,364,364,2,364,2010,Epidemic,10_19
3,2700409,24.897218,81.989589,423.138619,364,364,4,364,2010,Episodic/Epidemic,10_19
4,2700508,25.800147,78.780638,491.421552,364,363,5,363,2010,Episodic,10_19

In [6]:
df_20_22 = pd.read_csv('../Determinantes/clima/clima_agg_20_22.csv', index_col = 'Unnamed: 0')

df_20_22.loc[:, 'dengue_pattern'] = df_20_22.dengue_pattern.replace(update_prof)

df_20_22['period'] = '20_22'

df_20_22.head()

,geocodigo,temp_med,umid_med,precip_tot,thr_temp,thr_umid,thr_prec,thr_temp_umid,year,dengue_pattern,period
0,2700102,26.368572,65.759019,79.313571,371,241,0,241,2020,Episodic/Epidemic,20_22
1,2700201,25.656351,78.530554,320.167782,371,371,3,371,2020,Episodic/Epidemic,20_22
2,2700300,25.839300,73.983355,187.897610,371,366,1,366,2020,Epidemic,20_22
3,2700409,25.007031,80.555151,336.263240,371,371,3,371,2020,Episodic/Epidemic,20_22
4,2700508,25.844227,79.239810,418.317611,371,371,4,371,2020,Episodic,20_22

In [9]:
col = 'temp_med'
perfil = 'No Transmission'

df_10_19_ = df_10_19.loc[df_10_19.dengue_pattern == perfil]
df_20_22_ = df_20_22.loc[df_20_22.dengue_pattern == perfil]

In [10]:
stats.ttest_ind(df_10_19_[col], df_20_22_[col])

TtestResult(statistic=-14.711051803866479, pvalue=2.993924770749467e-47, df=2810.0)

In [13]:
col = 'temp_med'
perfil = 'Persistent Transmission'

df_10_19_ = df_10_19.loc[df_10_19.dengue_pattern == perfil]
df_20_22_ = df_20_22.loc[df_20_22.dengue_pattern == perfil]

In [17]:
stats.ttest_ind(df_10_19_[col], df_20_22_[col]).pvalue

0.8949650997760927

In [19]:
df_20_22.dengue_pattern.unique()

array(['Episodic/Epidemic', 'Epidemic', 'Episodic',
       'Persistent Transmission', 'No Transmission'], dtype=object)

In [37]:

df_p = pd.DataFrame()
for col in ['temp_med', 'umid_med', 'precip_tot', 'thr_temp',
       'thr_umid', 'thr_prec', 'thr_temp_umid']:
    p_values = np.array([])
    for perfil in ['Episodic/Epidemic', 'Epidemic', 'Episodic',
       'Persistent Transmission', 'No Transmission']:
        #print(perfil)

        df_10_19_ = df_10_19.loc[df_10_19.dengue_pattern == perfil]
        df_20_22_ = df_20_22.loc[df_20_22.dengue_pattern == perfil]

        p_values = np.append(p_values, 
                            stats.ttest_ind(df_10_19_[col], df_20_22_[col]).pvalue)

    df_p_ = pd.DataFrame([p_values], columns = ['Episodic/Epidemic', 'Epidemic', 'Episodic',
       'Persistent Transmission', 'No Transmission'], index = [col])

    df_p = pd.concat([df_p, df_p_])

df_p

,Episodic/Epidemic,Epidemic,Episodic,Persistent Transmission,No Transmission
temp_med,9.287198e-118,8.796471e-35,2.788769e-02,0.894965,2.993925e-47
umid_med,8.860488e-01,5.082390e-31,8.135109e-13,0.841528,1.933563e-09
precip_tot,6.553541e-01,3.806718e-04,7.767165e-42,0.361678,3.901175e-17
thr_temp,1.442259e-96,1.841467e-33,8.545598e-10,0.958346,3.404343e-45
thr_umid,9.952030e-05,7.913446e-23,5.692366e-01,0.360301,5.313760e-07
thr_prec,7.155527e-21,2.285846e-03,4.291991e-24,0.008627,3.756181e-81
thr_temp_umid,5.306072e-42,1.602012e-64,5.201787e-09,0.608651,7.837992e-39

In [41]:
def color_cells(val):
    color = 'background-color: red' if val > 0.05 else ''
    return color

# Apply the function to the DataFrame to color the cells
df_p.style.applymap(color_cells)

/var/folders/ch/kxpr39wx44v97968yr_4hmch0000gn/T/ipykernel_46868/1422886589.py:6: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  df_p.style.applymap(color_cells)